[package]
name = "i2a-rs"
version = "0.1.0"
authors = ["hsfzxjy <hsfzxjy@163.com>"]
edition = "2018"

[dependencies]
image = "0.21.2"
lazy_static = "1.3.0"
clap = "2.33.0"
crossterm = "0.9.5"
term_size = "0.3.1"
data-encoding = "2.1.2"
ring = "0.14.6"

[features]
gif_codec = []
